branches:
  only:
    - master

notifications:
  email:
    recipients:
      - nicolas.lecureuil@siveo.net
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc01.siveo.net#main"
    on_success: always #|never|change] # default: always
    on_failure: always #|never|change] # default: always
